---
  admin:
    access_log_path: "/tmp/admin_access.log"
    address:
      socket_address:
        address: "127.0.0.1"
        port_value: 9901
  static_resources:
    listeners:
      -
        name: "grpc-listener"
        address:
          socket_address:
            address: "0.0.0.0"
            port_value: 8787
        filter_chains:
          -
            filters:
              -
                name: "envoy.http_connection_manager"
                config:
                  stat_prefix: "ingress_http"
                  codec_type: "AUTO"
                  generate_request_id: true
                  route_config:
                    name: "todo-grpc-hello-route"
                    virtual_hosts:
                      -
                        name: "todo-grpc-hello-route"
                        domains:
                          - "*"
                        routes:
                          -
                            match:
                              prefix: "/"
                            route:
                              cluster: "todo_grpc_hello"
                  http_filters:
                    -
                      name: "envoy.router"
    clusters:

      -
        name: "todo_grpc_hello"
        connect_timeout: "0.25s"
        type: "strict_dns"
        lb_policy: "ROUND_ROBIN"
        http2_protocol_options: {}
        hosts:
          -
            socket_address:
              address: "127.0.0.1"
              port_value: 7778
